const easedRotation = {
  a: 1,
  k: [
    {
      t: 0,
      s: [0],
      e: [360],
      i: { x: [0.667], y: [1] },
      o: { x: [0.333], y: [0] },
    },
    { t: 90, s: [360] },
  ],
};

const staticTransform = {
  a: { a: 0, k: [0, 0] },
  p: { a: 0, k: [110, 110] },
  s: { a: 0, k: [100, 100] },
  r: { a: 0, k: 0 },
  o: { a: 0, k: 100 },
  sk: { a: 0, k: 0 },
  sa: { a: 0, k: 0 },
};

export const preloaderAnimation = {
  v: "5.7.4",
  fr: 30,
  ip: 0,
  op: 90,
  w: 220,
  h: 220,
  nm: "Orange Open Orbit",
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: "Orbit ring",
      sr: 1,
      ks: staticTransform,
      ao: 0,
      shapes: [
        {
          ty: "el",
          d: 1,
          s: { a: 0, k: [152, 152] },
          p: { a: 0, k: [0, 0] },
          nm: "Outer circle",
        },
        {
          ty: "st",
          c: { a: 0, k: [0.13, 0.08, 0.06, 0.55] },
          o: { a: 0, k: 100 },
          w: { a: 0, k: 1.5 },
          lc: 2,
          lj: 2,
          ml: 4,
          bm: 0,
          nm: "Fine stroke",
        },
        {
          ty: "tr",
          p: { a: 0, k: [0, 0] },
          a: { a: 0, k: [0, 0] },
          s: { a: 0, k: [100, 100] },
          r: { a: 0, k: 0 },
          o: { a: 0, k: 100 },
          sk: { a: 0, k: 0 },
          sa: { a: 0, k: 0 },
          nm: "Transform",
        },
      ],
      ip: 0,
      op: 90,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 2,
      ty: 4,
      nm: "Orbiting cue ball",
      sr: 1,
      ks: {
        ...staticTransform,
        r: easedRotation,
      },
      ao: 0,
      shapes: [
        {
          ty: "el",
          d: 1,
          s: { a: 0, k: [20, 20] },
          p: { a: 0, k: [75, 0] },
          nm: "Cue ball",
        },
        {
          ty: "fl",
          c: { a: 0, k: [1, 0.94, 0.84, 1] },
          o: { a: 0, k: 100 },
          r: 1,
          bm: 0,
          nm: "Ivory fill",
        },
        {
          ty: "tr",
          p: { a: 0, k: [0, 0] },
          a: { a: 0, k: [0, 0] },
          s: { a: 0, k: [100, 100] },
          r: { a: 0, k: 0 },
          o: { a: 0, k: 100 },
          sk: { a: 0, k: 0 },
          sa: { a: 0, k: 0 },
          nm: "Transform",
        },
      ],
      ip: 0,
      op: 90,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 3,
      ty: 4,
      nm: "Center",
      sr: 1,
      ks: staticTransform,
      ao: 0,
      shapes: [
        {
          ty: "el",
          d: 1,
          s: { a: 0, k: [56, 56] },
          p: { a: 0, k: [0, 0] },
          nm: "Center circle",
        },
        {
          ty: "fl",
          c: { a: 0, k: [0.15, 0.075, 0.045, 1] },
          o: { a: 0, k: 100 },
          r: 1,
          bm: 0,
          nm: "Ink fill",
        },
        {
          ty: "tr",
          p: { a: 0, k: [0, 0] },
          a: { a: 0, k: [0, 0] },
          s: { a: 0, k: [100, 100] },
          r: { a: 0, k: 0 },
          o: { a: 0, k: 100 },
          sk: { a: 0, k: 0 },
          sa: { a: 0, k: 0 },
          nm: "Transform",
        },
      ],
      ip: 0,
      op: 90,
      st: 0,
      bm: 0,
    },
  ],
};
